<?php

namespace AppBundle\Repository;

/**
 * userShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userShopRepository extends \Doctrine\ORM\EntityRepository
{
}
