<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /*
    public function findOneUser($username)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('u');

        $query = $qb->select('u')
            ->from('AppBundle\Entity\User', 'u')

            ->where($qb->expr()->like('u.username','?1'))


            ->setParameter(1,'%'.$username.'%')

        ;
        return $query->getQuery()->getOneOrNullResult();
    }
    */
    public function findStudentsByNiveau($groupe)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $query = $qb->select('u')
            ->from('AppBundle\Entity\User', 'u')
            ->where(':niveau MEMBER OF u.niveaux')
            ->andWhere('u.isChild=:state')
            ->setParameters(array(
                "niveau" => $groupe,
                "state" => true
            ))
        ;

        return $query->getQuery()->getResult();
    }
}
